import { MAX_CODEX_THREAD_LIST_LIMIT } from './aliases.js';

export function buildHelpCommandResponse(): string {
  return [
    '**命令速览**',
    '',
    '**常用**',
    '- `/` 当前聊天/当前会话诊断',
    '- `/status` 全局状态（通道、Bridge/UI 进程、PID、绑定与会话数量）',
    '- `/check` 健康检查',
    '- `/check all` 查看所有运行中会话的健康状态',
    '- `//...` 向模型发送以 `/` 开头的文本',
    '- `/h` 帮助',
    `- \`/t\` 文本默认最近 10 条，卡片最多 ${MAX_CODEX_THREAD_LIST_LIMIT} 条本地 Codex 会话`,
    `- \`/t all\` 文本和卡片都最多 ${MAX_CODEX_THREAD_LIST_LIMIT} 条本地 Codex 会话`,
    `- \`/t n 100\` 最近 100 条本地 Codex 会话（最多 ${MAX_CODEX_THREAD_LIST_LIMIT} 条）`,
    '- `/t 1` 接管第 1 条会话，并设为当前线程',
    '- `/t ls` 查看当前聊天已绑定线程',
    '- `/t attach 1` 绑定第 1 条本地 Codex 会话但不切走当前线程',
    '- `/t archive` 归档当前本地 Codex 会话并解除相关绑定；也可用 `/t archive 1` 按 `/t` 全局表序号指定会话',
    '- `/t use 1` 切换当前绑定线程（也可用 bridge session id、thread id、binding id 或名称）',
    '- `/t detach 1` 解绑指定绑定线程（也可用 bridge session id、thread id、binding id 或名称）',
    '- `/t rename <名称>` 重命名当前线程',
    '- 序号范围：`/t 1`、`/t attach 1` 和 `/t archive 1` 使用 `/t` 全局 Bridge / Codex 会话表；`/t use 1` 和 `/t detach 1` 使用 `/t ls` 当前聊天局部绑定表',
    '- `/n` 在当前工作目录下新建线程（仅保证 IM 可继续，不会自动出现在本地 Codex 会话列表）',
    '- `/n proj1` 在默认工作空间下新建项目会话',
    '- 直接发文本：继续当前会话；未绑定时进入临时草稿线程',
    '- `/his` 最近消息卡片（等同 `/his msg`，优先 Codex session JSONL，找不到再读 Bridge 缓存）',
    '- `/his msg [1-20]` 最近消息卡片，可临时指定本次条数',
    '- `/his json` 直接发送原始 session JSONL 文件',
    '- `/his limit 12` 修改 `/his msg` 默认返回条数（1-20）',
    '- `/shell [秒数] <command>`（新特性）在当前会话目录用 `codex sandbox` 流式执行命令；默认允许网络；卡片刷新最低 5 秒；高风险命令需追加 `--force`',
    '- `/hot-update` 使用当前 Bridge 环境派发本项目热更新，并每 10 秒刷新 hot update log 卡片；`/hot-update --dry-run` 只检查不执行',
    '- `/auto ls` 查看当前 bridge session 的自动化任务',
    '- `/auto new <scriptpath> <times>` 创建自动化任务；脚本 stdout 会作为下一轮 Codex prompt',
    '- `/auto rm <序号>` 删除自动化任务',
    '- `/auto set <序号> <times>` 重置触发次数并设置总次数；`0` 表示暂停',
    '- `/auto skill install|uninstall` 安装或删除自动脚本创建 skill',
    '- `/tmux-switch` 列出 tmux sessions，类似 `Ctrl+b s`',
    '- `/tmux-attach <session>` 绑定当前 IM 会话的远程 tmux session',
    '- `/tmux-new [session]` 新建并绑定 tmux session；已存在则提示并直接绑定',
    '- `/tmux-status` 查看当前绑定和截屏行数',
    '- `/tmux-set lines 120` 设置 `/tmux` 自动截屏行数',
    '- `/tmux-set enter on|off` 设置 `/tmux` 发送内容后是否自动补 Enter',
    '- `/tmux-screen [lines] [seconds]s` 查看当前绑定 tmux session 的屏幕状态；例如 `/tmux-screen 5s` 或 `/tmux-screen 120 5s`，最低 3 秒',
    '- `/tmux-screen stop` 停止当前聊天的 tmux 屏幕定时刷新',
    '- `/tmux pwd<Enter>` 向当前 tmux session 发送按键并自动截屏返回',
    '',
    '**设置**',
    '- `/m` 查看模式；可用 `normal | yolo`（`code` 会映射为 `normal`）',
    '- `/provider` 查看或切换 Codex Provider；可用 `sdk | tmux`',
    '- `/r` 查看思考级别；可用 `1 | 2 | 3 | 4 | 5`',
    '- `/sb` 查看或切换 Codex 沙箱；可用 `read-only | workspace-write | danger-full-access | default`',
    '- `/net` 查看或切换 Codex 网络；可用 `on | off | default`',
    '- `/ui` 查看 UI 显示设置；`/ui on|off` 切换 SDK 工具输入输出显示',
    '- `/model` 查看当前模型；`/model gpt-5.4` 可切换，`/model default` 回退到默认模型',
    '- `/set` 查看全局配置；`/set <key> <value>` 修改 UI 设置页里的非 channel 配置',
    '- `/t 0` 临时草稿线程',
    '- `/t 0 reset` 重置草稿线程',
    '- `/stop` 停止当前任务',
    '',
    '**其它**',
    '- `/his raw [1-20]` 解析后的纯文本视图，可临时指定本次条数',
    '- `/his json` 直接发送原始 session JSONL 文件（兼容别名：`/his file`）',
    '- `/shell --sandbox read-only|workspace-write [秒数] <command>` 指定本次 shell sandbox；不允许 danger-full-access；IM 自动链接会按显示文本执行',
    '- `/perm allow|allow_session|deny <id>` 或 `1 / 2 / 3` 处理权限',
    '- `/cat <path> [start] [end]` 打印文件内容（默认前 200 行）',
    '- `/file <path>` 直接发送本地文件',
  ].join('\n');
}
